trigger:
  branches:
    include:
      - main
      - feature/*
      - fix/*
      - release/*

pool:
  vmImage: ubuntu-latest

variables:
  - group: Migration-pipeline-varG

  - name: dockerRegistryServiceConnection
    value: acr-service-connection

  - name: sonarServiceConnection
    value: sonar-service-connection

  - name: imageRepositoryUserAuth
    value: user-auth-service

  - name: imageRepositoryInsurance
    value: insurance-service

stages:

# ======================================================
# VERSION CALCULATION
# ======================================================

- stage: CalculateVersion
  displayName: Calculate Semantic Versions

  jobs:
    - job: Versioning
      displayName: Calculate Auth and Insurance Versions

      steps:
        - checkout: self

        - script: |
            set -e

            git clone https://$(HELM_PAT)@dev.azure.com/yadavkartik0506/MS-migration/_git/Central-Helm

            cd Central-Helm

            BRANCH="$(Build.SourceBranch)"

            echo "Branch: $BRANCH"

            bump_version() {
              VERSION_FILE=$1

              VERSION=$(cat $VERSION_FILE)

              IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

              if [[ "$BRANCH" == refs/heads/fix/* ]]; then
                PATCH=$((PATCH+1))

              elif [[ "$BRANCH" == refs/heads/feature/* ]]; then
                MINOR=$((MINOR+1))
                PATCH=0

              elif [[ "$BRANCH" == refs/heads/release/* ]]; then
                MAJOR=$((MAJOR+1))
                MINOR=0
                PATCH=0
              fi

              echo "$MAJOR.$MINOR.$PATCH"
            }

            AUTH_VERSION=$(bump_version versions/auth.version)

            INSURANCE_VERSION=$(bump_version versions/insurance.version)

            echo "Auth Version: $AUTH_VERSION"
            echo "Insurance Version: $INSURANCE_VERSION"

            echo "##vso[task.setvariable variable=authImageTag;isOutput=true]$AUTH_VERSION"
            echo "##vso[task.setvariable variable=insuranceImageTag;isOutput=true]$INSURANCE_VERSION"
          name: VersionStep

# ======================================================
# SONARQUBE
# ======================================================

# - stage: CodeQuality
#   dependsOn: CalculateVersion

#   jobs:
#     - job: Sonar

#       steps:
#         - checkout: self

#         - task: SonarQubePrepare@5
#           inputs:
#             SonarQube: $(sonarServiceConnection)
#             scannerMode: CLI
#             configMode: manual
#             cliProjectKey: InsurancePlatform
#             cliProjectName: InsurancePlatform

#         - script: |
#             dotnet build
#           displayName: Build Solution

#         - task: SonarQubeAnalyze@5

#         - task: SonarQubePublish@5
#           inputs:
#             pollingTimeoutSec: 300

# ======================================================
# BUILD AND PUSH
# ======================================================

- stage: Build
  dependsOn: CalculateVersion
  # condition: and(succeeded(), false)
  variables:
    authImageTag: $[ stageDependencies.CalculateVersion.Versioning.outputs['VersionStep.authImageTag'] ]
    insuranceImageTag: $[ stageDependencies.CalculateVersion.Versioning.outputs['VersionStep.insuranceImageTag'] ]

  jobs:
    - job: BuildUserAuth
      displayName: Build User Auth Service

      steps:

      - script: |
          echo "Auth Tag = $(authImageTag)"
          echo "Insurance Tag = $(insuranceImageTag)"
        displayName: Debug Tags

      - task: Docker@2
        inputs:
          command: buildAndPush
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: $(imageRepositoryUserAuth)
          dockerfile: userAuthService/Dockerfile
          tags: |
            $(authImageTag)

    - job: BuildInsurance
      displayName: Build Insurance Service

      steps:
        - task: Docker@2
          inputs:
            command: buildAndPush
            containerRegistry: $(dockerRegistryServiceConnection)
            repository: $(imageRepositoryInsurance)
            dockerfile: insuranceService/Dockerfile
            tags: |
              $(insuranceImageTag)

# ======================================================
# UPDATE HELM REPO
# ======================================================

- stage: UpdateHelmRepo
  dependsOn: Build

  variables:
    authImageTag: $[ stageDependencies.CalculateVersion.Versioning.outputs['VersionStep.authImageTag'] ]
    insuranceImageTag: $[ stageDependencies.CalculateVersion.Versioning.outputs['VersionStep.insuranceImageTag'] ]

  jobs:
    - job: UpdateHelm
      displayName: Update Helm Repo

      steps:
        - checkout: none

        - script: |
            set -e

            git config --global user.email "yadavkartik0506@outlook.com"
            git config --global user.name "kartikey yadav"

            git clone https://$(HELM_PAT)@dev.azure.com/yadavkartik0506/MS-migration/_git/Central-Helm

            cd Central-Helm

            sed -i "s/tag:.*/tag: $(authImageTag)/" environments/dev/auth-image.yaml

            sed -i "s/tag:.*/tag: $(insuranceImageTag)/" environments/dev/insurance-image.yaml

            echo "$(authImageTag)" > versions/auth.version

            echo "$(insuranceImageTag)" > versions/insurance.version

            git add .

            git commit -m "Release Auth $(authImageTag) | Insurance $(insuranceImageTag)"

            git push origin main
          displayName: Commit Helm Changes
